version = 0.1
[default.deploy.parameters]
stack_name = "headsupbackend"
resolve_s3 = true
s3_prefix = "headsupbackend"
region = "us-west-2"
profile = "coderavels-admin"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
